export const allDepartmentJson = [
  { id: 1, name: "Accounting" },
  { id: 2, name: "Finance" },
  { id: 3, name: "Sales" },
  { id: 4, name: "Research & Development" },
  { id: 5, name: "IT" },
  { id: 6, name: "Management" },
  { id: 7, name: "Administration" },
  { id: 8, name: "Customer Service" },
  { id: 9, name: "Customer Support" },
  { id: 10, name: "Technical Support" },
  { id: 11, name: "Marketing" },
  { id: 12, name: "Operations" },
  { id: 13, name: "Logistics" },
  { id: 14, name: "Planning" },
  { id: 15, name: "Purchasing" },
  { id: 16, name: "Quality Assurance" },
  { id: 17, name: "Engineering" },
  { id: 18, name: "Export" },
  { id: 19, name: "Shipping" },
  { id: 20, name: "Public Relations" },
  { id: 21, name: "Production" },
  { id: 22, name: "Supervision" },
  { id: 23, name: "Product Quality" },
  { id: 24, name: "Inventory" },
];
