export const designationListJson = [
    { id: 1, name: "CEO" },
    { id: 2, name: "MD" },
    { id: 3, name: "Director" },
    { id: 4, name: "Manager" },
    { id: 5, name: "Executive" },
    { id: 6, name: "Managing Director" },
    { id: 7, name: "Account Collector" },
    { id: 8, name: "Account Executive" },
    { id: 9, name: "Account Manager" },
    { id: 10, name: "Accountant" },
    { id: 11, name: "Accounting Analyst" },
    { id: 12, name: "Accounting Director" },
    { id: 13, name: "Accounts Payable/Receivable Clerk" },
    { id: 14, name: "Actor" },
    { id: 15, name: "Actuary" },
    { id: 16, name: "Addiction Counselor" },
    { id: 17, name: "Administrative Analyst" },
    { id: 18, name: "Administrative Assistant" },
    { id: 19, name: "Administrative Manager" },
    { id: 20, name: "Administrative Specialist" },
    { id: 21, name: "Administrator" },
    { id: 22, name: "Animal Breeder" },
    { id: 23, name: "Animal Control Officer" },
    { id: 24, name: "Animal Shelter Board Member" },
    { id: 25, name: "Animal Shelter Manager" },
    { id: 26, name: "Animal Shelter Volunteer" },
    { id: 27, name: "Animal Shelter Worker" },
    { id: 28, name: "Animal Trainer" },
    { id: 29, name: "Application Developer" },
    { id: 30, name: "Architect" },
    { id: 31, name: "Archivist" },
    { id: 32, name: "Area Sales Manager" },
    { id: 33, name: "Artificial Intelligence Engineer" },
    { id: 34, name: "Artist" },
    { id: 35, name: "Assistant Engineer" },
    { id: 36, name: "Assistant Golf Professional" },
    { id: 37, name: "Assistant Manager" },
    { id: 38, name: "Assistant Professor" },
    { id: 39, name: "Astronomer" },
    { id: 40, name: "Atmospheric Scientist" },
    { id: 41, name: "Attorney" },
    { id: 42, name: "Auditing Clerk" },
    { id: 43, name: "Auditor" },
    { id: 44, name: "B2B Sales Specialist" },
    { id: 45, name: "Bank Teller" },
    { id: 46, name: "Barber" },
    { id: 47, name: "Barista" },
    { id: 48, name: "Beautician" },
    { id: 49, name: "Bellhop" },
    { id: 50, name: "Benefits Manager" },
    { id: 51, name: "Biological Engineer" },
    { id: 52, name: "Biologist" },
    { id: 53, name: "Biostatistician" },
    { id: 54, name: "Boilermaker" },
    { id: 55, name: "Bookkeeper" },
    { id: 56, name: "Branch Manager" },
    { id: 57, name: "Brand Manager" },
    { id: 58, name: "Brand Strategist" },
    { id: 59, name: "Budget Analyst" },
    { id: 60, name: "Building Inspector" },
    { id: 61, name: "Bus Driver" },
    { id: 62, name: "Bus Person" },
    { id: 63, name: "Business Analyst" },
    { id: 64, name: "Business Manager" },
    { id: 65, name: "Cab Driver" },
    { id: 66, name: "Cafeteria Worker" },
    { id: 67, name: "Call Center Representative" },
    { id: 68, name: "Camera Operator" },
    { id: 69, name: "Caregiver" },
    { id: 70, name: "Caretaker or House Sitter" },
    { id: 71, name: "Carpenter" },
    { id: 72, name: "Cashier" },
    { id: 73, name: "Casino Host" },
    { id: 74, name: "Chef" },
    { id: 75, name: "Chemical Engineer" },
    { id: 76, name: "Chemist" },
    { id: 77, name: "Chief" },
    { id: 78, name: "Chief Customer Officer" },
    { id: 79, name: "Chief Data Officer" },
    { id: 80, name: "Chief Engineer" },
    { id: 81, name: "Chief Executive Officer" },
    { id: 82, name: "Chief Financial Officer" },
    { id: 83, name: "Chief Human Resources Officer" },
    { id: 84, name: "Chief Information Officer" },
    { id: 85, name: "Chief Marketing Officer" },
    { id: 86, name: "Chief Operating Officer" },
    { id: 87, name: "Chief People Officer" },
    { id: 88, name: "Chief Product Officer" },
    { id: 89, name: "Chief Robot Whisperer" },
    { id: 90, name: "Chief Technology Officer" },
    { id: 91, name: "Church Volunteer" },
    { id: 92, name: "Civil Engineer" },
    { id: 93, name: "Cloud Architect" },
    { id: 94, name: "CNA" },
    { id: 95, name: "Columnist" },
    { id: 96, name: "Commercial Loan Officer" },
    { id: 97, name: "Communications Director" },
    { id: 98, name: "Community Food Project Worker" },
    { id: 99, name: "Community Volunteer Jobs" },
    { id: 100, name: "Computer Animator" },
    { id: 101, name: "Computer Programmer" },
    { id: 102, name: "Computer Scientist" },
    { id: 103, name: "Concierge" },
    { id: 104, name: "Conservation Scientist" },
    { id: 105, name: "Conservation Volunteer" },
    { id: 106, name: "Construction Worker" },
    { id: 107, name: "Content Creator" },
    { id: 108, name: "Content Marketing Manager" },
    { id: 109, name: "Content Strategist" },
    { id: 110, name: "Continuous Improvement Consultant" },
    { id: 111, name: "Continuous Improvement Lead" },
    { id: 112, name: "Controller" },
    { id: 113, name: "Coordinator" },
    { id: 114, name: "Copy Editor" },
    { id: 115, name: "Copywriter" },
    { id: 116, name: "Cosmetologist" },
    { id: 117, name: "Counselor" },
    { id: 118, name: "Couples Counselor" },
    { id: 119, name: "Courier" },
    { id: 120, name: "Crane Operator" },
    { id: 121, name: "Credit Authorizer" },
    { id: 122, name: "Credit Counselor" },
    { id: 123, name: "Cruise Director" },
    { id: 124, name: "Cruise Ship Attendant" },
    { id: 125, name: "Culture Operations Manager" },
    { id: 126, name: "Customer Service" },
    { id: 127, name: "Customer Support Representative" },
    { id: 128, name: "Data Analyst" },
    { id: 129, name: "Data Entry" },
    { id: 130, name: "Delivery Driver" },
    { id: 131, name: "Dental Hygienist" },
    { id: 132, name: "DevOps Engineer" },
    { id: 133, name: "Digital Marketing Manager" },
    { id: 134, name: "Digital Overlord" },
    { id: 135, name: "Direct Salesperson" },
    { id: 136, name: "Director" },
    { id: 137, name: "Director of Bean Counting" },
    { id: 138, name: "Director of Ethical Hacking" },
    { id: 139, name: "Director of First Impressions" },
    { id: 140, name: "Director of Inside Sales" },
    { id: 141, name: "Director of Maintenance" },
    { id: 142, name: "Director of Photography" },
    { id: 143, name: "Director of Storytelling" },
    { id: 144, name: "Dispatcher for Trucks or Taxis" },
    { id: 145, name: "Doctor" },
    { id: 146, name: "Dog Walker / Pet Sitter" },
    { id: 147, name: "Drafter" },
    { id: 148, name: "eCommerce Marketing Specialist" },
    { id: 149, name: "Economist" },
    { id: 150, name: "Editor/Proofreader" },
    { id: 151, name: "Electrical Engineer" },
    { id: 152, name: "Electrician" },
    { id: 153, name: "Emergency Relief Worker" },
    { id: 154, name: "Engineer" },
    { id: 155, name: "Engineering Technician" },
    { id: 156, name: "Entertainment Specialist" },
    { id: 157, name: "Entrepreneur" },
    { id: 158, name: "Esthetician" },
    { id: 159, name: "Event Planner" },
    { id: 160, name: "Events Manager" },
    { id: 161, name: "Executive" },
    { id: 162, name: "Executive Assistant" },
    { id: 163, name: "Farm Worker" },
    { id: 164, name: "Fast Food Worker" },
    { id: 165, name: "File Clerk" },
    { id: 166, name: "Film Critic" },
    { id: 167, name: "Finance Director" },
    { id: 168, name: "Finance Manager" },
    { id: 169, name: "Financial Analyst" },
    { id: 170, name: "Financial Planner" },
    { id: 171, name: "Financial Services Representative" },
    { id: 172, name: "Flight Attendant" },
    { id: 173, name: "Food Kitchen Worker" },
    { id: 174, name: "Foreman" },
    { id: 175, name: "Founder" },
    { id: 176, name: "Front Desk Associate" },
    { id: 177, name: "Front Desk Manager" },
    { id: 178, name: "Funeral Attendant" },
    { id: 179, name: "Geological Engineer" },
    { id: 180, name: "Geologist" },
    { id: 181, name: "Ghostwriter" },
    { id: 182, name: "Grant Writer" },
    { id: 183, name: "Graphic Designer" },
    { id: 184, name: "Group Sales" },
    { id: 185, name: "Guidance Counselor" },
    { id: 186, name: "Habitat for Humanity Builder" },
    { id: 187, name: "Hair Stylist" },
    { id: 188, name: "Handyman" },
    { id: 189, name: "Head" },
    { id: 190, name: "Heavy Equipment Operator" },
    { id: 191, name: "Help Desk Worker/Desktop Support" },
    { id: 192, name: "Homeless Shelter Worker" },
    { id: 193, name: "Hospital Volunteer" },
    { id: 194, name: "Hotel Front Door Greeter" },
    { id: 195, name: "Hotel Manager" },
    { id: 196, name: "Hotel Receptionist" },
    { id: 197, name: "Housekeeper" },
    { id: 198, name: "Human Resources" },
    { id: 199, name: "HVAC Technician" },
    { id: 200, name: "Information Security Analyst" },
    { id: 201, name: "Interior Designer" },
    { id: 202, name: "Iron Worker" },
    { id: 203, name: "IT Manager" },
    { id: 204, name: "IT Professional" },
    { id: 205, name: "Journalist" },
    { id: 206, name: "Landscaping Assistant" },
    { id: 207, name: "Landscaping Worker" },
    { id: 208, name: "Lead" },
    { id: 209, name: "Library Assistant" },
    { id: 210, name: "Life Coach" },
    { id: 211, name: "Line Cook" },
    { id: 212, name: "Locksmith" },
    { id: 213, name: "Lodging Manager" },
    { id: 214, name: "Machinery Operator" },
    { id: 215, name: "Mail Carrier" },
    { id: 216, name: "Maintenance Engineer" },
    { id: 217, name: "Makeup Artist" },
    { id: 218, name: "Management Consultant" },
    { id: 219, name: "Manager" },
    { id: 220, name: "Managing Member" },
    { id: 221, name: "Managing Partner" },
    { id: 222, name: "Manicurist" },
    { id: 223, name: "Manufacturing Assembler" },
    { id: 224, name: "Market Development Manager" },
    { id: 225, name: "Market Researcher" },
    { id: 226, name: "Marketing Communications Manager" },
    { id: 227, name: "Marketing Consultant" },
    { id: 228, name: "Marketing Director" },
    { id: 229, name: "Marketing Manager" },
    { id: 230, name: "Marketing Research Analyst" },
    { id: 231, name: "Marketing Specialist" },
    { id: 232, name: "Mason" },
    { id: 233, name: "Massage Therapy" },
    { id: 234, name: "Mathematician" },
    { id: 235, name: "Meals on Wheels Driver" },
    { id: 236, name: "Mechanic" },
    { id: 237, name: "Mechanical Engineer" },
    { id: 238, name: "Media Buyer" },
    { id: 239, name: "Media Relations Coordinator" },
    { id: 240, name: "Medical Administrator" },
    { id: 241, name: "Medical Laboratory Tech" },
    { id: 242, name: "Medical Researcher" },
    { id: 243, name: "Medical Transcriptionist" },
    { id: 244, name: "Meeting Planner" },
    { id: 245, name: "Mental Health Counselor" },
    { id: 246, name: "Mentor" },
    { id: 247, name: "Merchandising Associate" },
    { id: 248, name: "Mining Engineer" },
    { id: 249, name: "Molecular Scientist" },
    { id: 250, name: "Mortgage Loan Processor" },
    { id: 251, name: "Motion Picture Director" },
    { id: 252, name: "Mover" },
    { id: 253, name: "Music Producer" },
    { id: 254, name: "Musician" },
    { id: 255, name: "Nail Technician" },
    { id: 256, name: "Network Administrator" },
    { id: 257, name: "Novelist/Writer" },
    { id: 258, name: "Nuclear Engineer" },
    { id: 259, name: "Nurse" },
    { id: 260, name: "Nurse Practitioner" },
    { id: 261, name: "Office Assistant" },
    { id: 262, name: "Office Clerk" },
    { id: 263, name: "Office Manager" },
    { id: 264, name: "Office Volunteer" },
    { id: 265, name: "Officer" },
    { id: 266, name: "Online ESL Instructor" },
    { id: 267, name: "Operations Analyst" },
    { id: 268, name: "Operations Assistant" },
    { id: 269, name: "Operations Coordinator" },
    { id: 270, name: "Operations Director" },
    { id: 271, name: "Operations Manager" },
    { id: 272, name: "Operations Professional" },
    { id: 273, name: "Orderly" },
    { id: 274, name: "Organizer" },
    { id: 275, name: "Outside Sales Manager" },
    { id: 276, name: "Over the Phone Interpreter" },
    { id: 277, name: "Overseer" },
    { id: 278, name: "Owner" },
    { id: 279, name: "Painter" },
    { id: 280, name: "Paralegal" },
    { id: 281, name: "Parking Attendant" },
    { id: 282, name: "Payroll Clerk" },
    { id: 283, name: "Payroll Manager" },
    { id: 284, name: "Personal Assistant" },
    { id: 285, name: "Personal Trainer" },
    { id: 286, name: "Petroleum Engineer" },
    { id: 287, name: "Pharmacist" },
    { id: 288, name: "Pharmacy Assistant" },
    { id: 289, name: "Phlebotomist" },
    { id: 290, name: "Phone Sales Specialist" },
    { id: 291, name: "Phone Survey Conductor" },
    { id: 292, name: "Photographer" },
    { id: 293, name: "Physical Therapist" },
    { id: 294, name: "Physical Therapy Assistant" },
    { id: 295, name: "Physicist" },
    { id: 296, name: "Pipefitter" },
    { id: 297, name: "Plant Engineer" },
    { id: 298, name: "Playwright" },
    { id: 299, name: "Plumber" },
    { id: 300, name: "Political Scientist" },
    { id: 301, name: "Porter" },
    { id: 302, name: "Preschool Teacher" },
    { id: 303, name: "President" },
    { id: 304, name: "Principal" },
    { id: 305, name: "Product Manager" },
    { id: 306, name: "Production Engineer" },
    { id: 307, name: "Professor" },
    { id: 308, name: "Program Administrator" },
    { id: 309, name: "Program Manager" },
    { id: 310, name: "Proposal Writer" },
    { id: 311, name: "Proprietor" },
    { id: 312, name: "Public Relations" },
    { id: 313, name: "Public Relations Specialist" },
    { id: 314, name: "Quality Control Coordinator" },
    { id: 315, name: "Quality Engineer" },
    { id: 316, name: "Real Estate Broker" },
    { id: 317, name: "Receptionist" },
    { id: 318, name: "Recruiter" },
    { id: 319, name: "Recyclables Collector" },
    { id: 320, name: "Red Cross Volunteer" },
    { id: 321, name: "Reiki Practitioner" },
    { id: 322, name: "Research Assistant" },
    { id: 323, name: "Researcher" },
    { id: 324, name: "Reservationist" },
    { id: 325, name: "Restaurant Chain Executive" },
    { id: 326, name: "Restaurant Manager" },
    { id: 327, name: "Retail Worker" },
    { id: 328, name: "Risk Manager" },
    { id: 329, name: "Roofer" },
    { id: 330, name: "Safety Engineer" },
    { id: 331, name: "Sales Analyst" },
    { id: 332, name: "Sales Associate" },
    { id: 333, name: "Sales Engineer" },
    { id: 334, name: "Sales Manager" },
    { id: 335, name: "Sales Representative" },
    { id: 336, name: "Salon Manager" },
    { id: 337, name: "School Bus Driver" },
    { id: 338, name: "School Counselor" },
    { id: 339, name: "School Volunteer" },
    { id: 340, name: "Screenwriter" },
    { id: 341, name: "Scrum Master" },
    { id: 342, name: "Secretary" },
    { id: 343, name: "Security Guard" },
    { id: 344, name: "SEO Manager" },
    { id: 345, name: "Server" },
    { id: 346, name: "Service Dog Trainer" },
    { id: 347, name: "Sheet Metal Worker" },
    { id: 348, name: "Shelf Stocker" },
    { id: 349, name: "Skin Care Specialist" },
    { id: 350, name: "Social Media Assistant" },
    { id: 351, name: "Social Media Specialist" },
    { id: 352, name: "Social Worker" },
    { id: 353, name: "Sociologist" },
    { id: 354, name: "Software Engineer" },
    { id: 355, name: "Software Ninjaneer" },
    { id: 356, name: "Solar Photovoltaic Installer" },
    { id: 357, name: "Sound Engineer" },
    { id: 358, name: "Spa Manager" },
    { id: 359, name: "Speech Pathologist" },
    { id: 360, name: "Speechwriter" },
    { id: 361, name: "Sports Volunteer" },
    { id: 362, name: "SQL Developer" },
    { id: 363, name: "Store Manager" },
    { id: 364, name: "Substitute Teacher" },
    { id: 365, name: "Suicide Hotline Volunteer" },
    { id: 366, name: "Superintendent" },
    { id: 367, name: "Supervisor" },
    { id: 368, name: "Taper" },
    { id: 369, name: "Teacher" },
    { id: 370, name: "Teaching Assistant" },
    { id: 371, name: "Team Leader" },
    { id: 372, name: "Technical Specialist" },
    { id: 373, name: "Technical Writer" },
    { id: 374, name: "Telemarketer" },
    { id: 375, name: "Telephone Operator" },
    { id: 376, name: "Telework Nurse/Doctor" },
    { id: 377, name: "Test Scorer" },
    { id: 378, name: "Therapist" },
    { id: 379, name: "Title Analyst" },
    { id: 380, name: "Title Researcher" },
    { id: 381, name: "Tow Truck Operator" },
    { id: 382, name: "Translator" },
    { id: 383, name: "Travel Agent" },
    { id: 384, name: "Travel Nurse" },
    { id: 385, name: "Travel Writer" },
    { id: 386, name: "Truck Driver" },
    { id: 387, name: "Tutor/Online Tutor" },
    { id: 388, name: "UPS Driver" },
    { id: 389, name: "UX Designer & UI Developer" },
    { id: 390, name: "Valet" },
    { id: 391, name: "Vehicle or Equipment Cleaner" },
    { id: 392, name: "Veterinary Assistant" },
    { id: 393, name: "Vice President of Marketing" },
    { id: 394, name: "Vice President of Operations" },
    { id: 395, name: "Video Editor" },
    { id: 396, name: "Video Game Writer" },
    { id: 397, name: "Video or Film Producer" },
    { id: 398, name: "VP of Miscellaneous Stuff" },
    { id: 399, name: "Wait Staff Manager" },
    { id: 400, name: "Waiter/Waitress" },
    { id: 401, name: "Warehouse Worker" },
    { id: 402, name: "Web Designer" },
    { id: 403, name: "Web Developer" },
    { id: 404, name: "Wedding Coordinator" },
    { id: 405, name: "Welder" },
    { id: 406, name: "Welding" },
    { id: 407, name: "Well Driller" },
    { id: 408, name: "Women’s Shelter Jobs" },
    { id: 409, name: "Yoga Instructor" },
    { id: 410, name: "Youth Volunteer" },
    { id: 411, name: "Zoologist" },
];